name: Release distribution

on:
  push:
    branches:
      - '**'
  delete:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --frozen-lockfile --non-interactive

      # - name: Compile
      #   run: yarn ttsc

      - name: Release
        uses: owner/repo@path
        with:
          push-branch: release-{branch}
          js-override-main: main.ts

  rebuild:
    runs-on: ubuntu-latest
    needs: [build_and_push]

    steps:
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract
        id: extract
        run: |
          echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"

      - name: Checkout pre-built
        uses: actions/checkout@v2
        with:
          ref: release-${{ steps.extract.outputs.branch }}
          path: prebuilt

      - name: Release
        uses: owner/prebuilt-repo@path
        if: github.event_name != 'delete'
        with:
          push-branch: release-{branch}
          js-override-main: main.ts
